name: Docker Image CI + Deploy

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build the Docker image BE
        run: |
          cd backend
          docker build -t vudinh2025/bloghomnay:latest .
          docker push vudinh2025/bloghomnay:latest

      - name: Build the Docker image FE
        run: |
          cd frontend/bloghomnay-project
          docker build -t vudinh2025/bloghomnay-fe:latest .
          docker push vudinh2025/bloghomnay-fe:latest

      - name: Deploy on VPS via SSH
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          password: ${{ secrets.VPS_PASSWORD }}
          script: |
            docker stop blog-frontend || true
            docker stop blog-backend || true
            docker rm blog-frontend || true
            docker rm blog-backend || true
            docker rmi blog-frontend || true
            docker rmi blog-backend || true

            docker run -d --name blog-backend \
              -p 3000:3000 \
              -e DB_HOST=14.225.206.78 \
              -e DB_PORT=1503 \
              -e DB_USER=sa \
              -e DB_PASSWORD='YourStrong!Passw0rd' \
              -e DB_NAME=bloghomnay \
              vudinh2025/bloghomnay:latest

            docker run -d --name blog-frontend \
              -p 80:80 \
              vudinh2025/bloghomnay-fe:latest
